version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      kubectl: latest
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - apt-get update && apt-get install -y awscli
      - export AWS_ACCESS_KEY_ID=AKIATCKAQ3KZ3AHT5KXS
      - export AWS_SECRET_ACCESS_KEY=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
      - aws eks --region us-east-1 update-kubeconfig --name demo
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g8y2p8o2
  build:
    commands:
      - echo "Construyendo la imagen de Docker..."
      - docker build -t my-custom-httpd-image .
      - echo "Etiquetando la imagen de Docker..."
      - docker tag my-custom-httpd-image:latest public.ecr.aws/g8y2p8o2/test-iavt12:my-custom-httpd-image
      - echo "Subiendo la imagen de Docker a Amazon ECR..."
      - docker push public.ecr.aws/g8y2p8o2/test-iavt12:my-custom-httpd-image
artifacts:
  files: []
